### ISSUE TITLE
Results for replicating Speech2Vec

### ISSUE THREAD

**Issue by JeromeNi** [my-yy/s2v_rc#1]
Hi, thanks for sharing your implementation of Speech2Vec!

I have several questions regarding the performance of this implementation:
1. How close have you come to the published results on word similarity on different benchmarks?
2. If the results are close, is training 500 epochs necessary to get close to the published results? When do you start getting diminishing returns?
3. Is there a parallel implementation available? 

Thanks!

**Comment by my-yy** [comment]
Hi, I failed to reproduce the Speech2Vec model. The model gets trivial results even after training for 500 epochs.
In fact, I wrote a report describing the encountered problem, and this repository is the code for that report. This report will be posted on arXiv this week.
As for other implementations, I haven't been able to find any successful third-party replications.

**Comment by my-yy** [comment]
The report is released at: https://arxiv.org/abs/2209.10791
Feel free to contact me if you have any suggestions :-) .
